### PR TITLE
Make PHP require 7.1 so it will match Laravel 5.8's PHP requirement

### PR DESCRIPTION
**Pull request by jamesj2**
Pull request for #18.

### CODE REVIEW

**Comment by hivokas** [comment]
Some checks were not successful (Scrutinizer — Analysis: No new issues – Tests: failed).

Fix, please.

**Comment by jamesj2** [comment]
I'm unsure how to fix this.  I'm not familiar with scrutinizer-ci.com.  It looks like the lover-file is in the wrong path.  Scrutinizer is expecting build/clover-file and the command `vendor/bin/phpunit --coverage-clover=clover-file` is putting in the root directory.  I couldn't find the config for this by searching the code.

**Comment by hivokas** [comment]
The problem is in PHP version.

```
This version of PHPUnit is supported on PHP 7.2, PHP 7.3, and PHP 7.4.
You are using PHP 7.1.12 (/home/scrutinizer/.phpenv/versions/7.1.12/bin/php).
```

**Comment by hivokas** [comment]
Sorry, I didn't see your last commit. Thanks!

**Comment by hivokas** [comment]
I've published the release.

**Pull request merged**
